# Generated by Django 3.0.1 on 2020-01-28 08:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Packages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('image', models.ImageField(default='img.jpg', upload_to='')),
                ('description', models.TextField(blank=True)),
                ('price', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'packages',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('image', models.ImageField(default='img.jpg', upload_to='')),
                ('contactno', models.CharField(max_length=50, null=True)),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='Bookings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('contactno', models.CharField(max_length=50)),
                ('date', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('numberofpeople', models.IntegerField()),
                ('packages', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Packages')),
            ],
            options={
                'db_table': 'bookings',
            },
        ),
    ]
